/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: [
    './html/**/*.twig',
    '../../modules/*/html_client/**/*.twig',
    '../../modules/*/html_admin/**/*.twig',
  ],
  safelist: [
    'grid-rows-[0fr]',
    'grid-rows-[1fr]',
    'blur-[100px]',
    'blur-[60px]',
    'blur-[80px]',
    'opacity-[0.15]',
    'opacity-[0.12]',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: 'var(--color-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        secondary: 'var(--color-secondary)',
        // ── Stitch design system ──
        'background':                  '#f8f9ff',
        'surface':                     '#ffffff',
        'surface-dim':                 '#cbdbf5',
        'surface-bright':              '#f8f9ff',
        'surface-container-lowest':    '#ffffff',
        'surface-container-low':       '#eff4ff',
        'surface-container':           '#e5eeff',
        'surface-container-high':      '#dce9ff',
        'surface-container-highest':   '#d3e4fe',
        'on-surface':                  '#0b1c30',
        'on-surface-variant':          '#484555',
        'inverse-surface':             '#213145',
        'inverse-on-surface':          '#eaf1ff',
        'outline':                     '#787587',
        'outline-variant':             '#c9c4d8',
        'surface-tint':                '#5c3de5',
        'primary-fixed':               '#e5deff',
        'primary-fixed-dim':           '#c8bfff',
        'on-primary-fixed':            '#190064',
        'on-primary-fixed-variant':    '#4317cd',
        'secondary-container':         '#d8dffb',
        'on-secondary-container':      '#5b6279',
        'tertiary-container':          '#596177',
        'on-tertiary-container':       '#d5ddf7',
        'error-container':             '#ffdad6',
        'on-error-container':          '#93000a',
        // ── extended grays ──
        gray: {
          950: '#030712',
          925: '#070c18',
          900: '#0f172a',
          800: '#1e293b',
          700: '#334155',
          600: '#475569',
          500: '#64748b',
          400: '#94a3b8',
          300: '#cbd5e1',
          200: '#e2e8f0',
          100: '#f1f5f9',
        },
      },
      borderRadius: {
        sm:      '0.125rem',
        DEFAULT: '0.25rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.625rem',
        '2xl':   '0.75rem',
        '3xl':   '0.875rem',
        full:    '9999px',
      },
      spacing: {
        'xs':            '4px',
        'sm':            '12px',
        'md':            '24px',
        'lg':            '32px',
        'xl':            '48px',
        'gutter':        '24px',
        'sidebar-width': '260px',
      },
      fontSize: {
        'h1':         ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2':         ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3':         ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg':    ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':    ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'status':     ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        'level-1': '0 1px 4px rgba(0,0,0,0.02), 0 0 0 1px rgba(0,0,0,0.04)',
        'level-2': '0 4px 12px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
