/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: [
    './html/**/*.twig',
    '../../modules/*/html_client/**/*.twig',
    '../../modules/*/html_admin/**/*.twig',
    '../../modules/*/templates/client/**/*.twig',
    '../../modules/*/templates/admin/**/*.twig',
  ],
  safelist: [
    'grid-rows-[0fr]',
    'grid-rows-[1fr]',
    'blur-[100px]',
    'blur-[60px]',
    'blur-[80px]',
    'opacity-[0.15]',
    'opacity-[0.12]',
    'font-display',
    'shadow-card',
    'shadow-card-hover',
    'shadow-btn',
    'shadow-hero',
    'text-brand-accent',
    'bg-brand-accent-surface',
    'text-brand-success',
    'bg-brand-success-surface',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Inter', '"Helvetica Neue"', 'Helvetica', 'Arial', 'system-ui', 'sans-serif'],
        display: ['"Inter Tight"', '"Helvetica Neue"', 'Helvetica', 'Arial', 'system-ui', 'sans-serif'],
        mono:    ['"JetBrains Mono"', '"Fira Code"', 'Consolas', 'monospace'],
      },
      colors: {
        primary: 'rgb(var(--brand-500) / <alpha-value>)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        secondary: 'rgb(var(--brand2-600) / <alpha-value>)',
        // ── Brand-mapped palettes ──
        // indigo/violet are remapped onto the admin-configured primary/secondary
        // colors (channel vars emitted by partials/theme_colors.html.twig).
        // Every indigo-*/violet-* utility — including opacity modifiers like
        // bg-indigo-500/10 — therefore follows the theme settings.
        indigo: {
          50:  'rgb(var(--brand-50) / <alpha-value>)',
          100: 'rgb(var(--brand-100) / <alpha-value>)',
          200: 'rgb(var(--brand-200) / <alpha-value>)',
          300: 'rgb(var(--brand-300) / <alpha-value>)',
          400: 'rgb(var(--brand-400) / <alpha-value>)',
          500: 'rgb(var(--brand-500) / <alpha-value>)',
          600: 'rgb(var(--brand-600) / <alpha-value>)',
          700: 'rgb(var(--brand-700) / <alpha-value>)',
          800: 'rgb(var(--brand-800) / <alpha-value>)',
          900: 'rgb(var(--brand-900) / <alpha-value>)',
          950: 'rgb(var(--brand-950) / <alpha-value>)',
        },
        violet: {
          50:  'rgb(var(--brand2-50) / <alpha-value>)',
          100: 'rgb(var(--brand2-100) / <alpha-value>)',
          200: 'rgb(var(--brand2-200) / <alpha-value>)',
          300: 'rgb(var(--brand2-300) / <alpha-value>)',
          400: 'rgb(var(--brand2-400) / <alpha-value>)',
          500: 'rgb(var(--brand2-500) / <alpha-value>)',
          600: 'rgb(var(--brand2-600) / <alpha-value>)',
          700: 'rgb(var(--brand2-700) / <alpha-value>)',
          900: 'rgb(var(--brand2-900) / <alpha-value>)',
        },
        // ── MeroVPS design tokens (matches WordPress theme) ──
        'background':                  '#fbf8ff',
        'surface':                     '#ffffff',
        'surface-dim':                 '#e8eaf8',
        'surface-bright':              '#fbf8ff',
        'surface-container-lowest':    '#ffffff',
        'surface-container-low':       '#f3f2fe',
        'surface-container':           '#eeedf9',
        'surface-container-high':      '#e8e8f5',
        'surface-container-highest':   '#e2e2f0',
        'on-surface':                  '#1a1b23',
        'on-surface-variant':          '#444655',
        'inverse-surface':             '#2e2f38',
        'inverse-on-surface':          '#f0f0ff',
        'outline':                     '#656879',
        'outline-variant':             '#c4c5d7',
        'surface-tint':                '#5271ff',
        'primary-fixed':               '#edf1ff',
        'primary-fixed-dim':           '#c0caff',
        'on-primary-fixed':            '#001270',
        'on-primary-fixed-variant':    '#3050db',
        'secondary-container':         '#dce3ff',
        'on-secondary-container':      '#1a3080',
        'tertiary-container':          '#e8eaff',
        'on-tertiary-container':       '#1a2060',
        'error-container':             '#ffdad6',
        'on-error-container':          '#93000a',
        // ── MeroVPS brand accent (AI/product eyebrow) ──
        'brand-accent':                '#bd540b',
        'brand-accent-surface':        '#fff3e9',
        // ── Success ──
        'brand-success':               '#159967',
        'brand-success-surface':       '#e8f8f1',
        // ── extended grays ──
        gray: {
          950: '#030712',
          925: '#070c18',
          900: '#0f172a',
          800: '#1e293b',
          700: '#334155',
          600: '#475569',
          500: '#64748b',
          400: '#94a3b8',
          300: '#cbd5e1',
          200: '#e2e8f0',
          100: '#f1f5f9',
        },
      },
      borderRadius: {
        sm:      '0.125rem',
        DEFAULT: '0.25rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.625rem',
        '2xl':   '0.75rem',
        '3xl':   '0.875rem',
        full:    '9999px',
      },
      spacing: {
        'xs':            '4px',
        'sm':            '12px',
        'md':            '24px',
        'lg':            '32px',
        'xl':            '48px',
        'gutter':        '24px',
        'sidebar-width': '260px',
      },
      fontSize: {
        'h1':         ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2':         ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3':         ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg':    ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':    ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'status':     ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        'level-1': '0 1px 4px rgba(31,42,85,0.04), 0 0 0 1px rgba(31,42,85,0.06)',
        'level-2': '0 4px 12px rgba(31,42,85,0.08)',
        'card':    '0 14px 35px rgba(31,42,85,0.05)',
        'card-hover': '0 22px 48px rgba(31,42,85,0.09)',
        'hero':    '0 35px 90px rgba(31,42,85,0.14)',
        'btn':     '0 13px 28px rgba(82,113,255,0.24)',
      },
    },
  },
  plugins: [],
};
