<?php

declare(strict_types=1);

/**
 * Migration Center — a client's request to migrate from a previous host.
 *
 * The encrypted secret is a private field with no getter on the API array
 * paths: neither toApiArray() nor toAdminApiArray() may ever include it or
 * its decrypted form. Only Service::revealSecret() decrypts, and only for
 * staff holding the manage_migrations permission.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

namespace Box\Mod\Migrationcenter\Entity;

use Box\Mod\Migrationcenter\Support\PanelType;
use Box\Mod\Migrationcenter\Support\RequestStatus;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use FOSSBilling\Interfaces\ApiArrayInterface;

#[ORM\Entity(repositoryClass: \Box\Mod\Migrationcenter\Repository\MigrationRequestRepository::class)]
#[ORM\Table(name: 'mod_migrationcenter_request')]
#[ORM\Index(name: 'idx_migrationcenter_client', columns: ['client_id'])]
#[ORM\Index(name: 'idx_migrationcenter_status', columns: ['status'])]
#[ORM\HasLifecycleCallbacks]
class MigrationRequest implements ApiArrayInterface
{
    public const string METHOD_MANUAL = 'manual';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (Doctrine entity ID is auto-generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT)]
    private int $clientId = 0;

    #[ORM\Column(name: 'client_order_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientOrderId = null;

    #[ORM\Column(type: Types::STRING, length: 20)]
    private string $status = RequestStatus::SUBMITTED;

    #[ORM\Column(type: Types::STRING, length: 20)]
    private string $method = self::METHOD_MANUAL;

    #[ORM\Column(name: 'panel_type', type: Types::STRING, length: 30)]
    private string $panelType = PanelType::OTHER;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $host = '';

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $port = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $username = '';

    #[ORM\Column(name: 'secret_encrypted', type: Types::TEXT)]
    private string $secretEncrypted = '';

    #[ORM\Column(name: 'secret_purged_at', type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $secretPurgedAt = null;

    #[ORM\Column(name: 'client_notes', type: Types::TEXT, nullable: true)]
    private ?string $clientNotes = null;

    #[ORM\Column(name: 'staff_notes', type: Types::TEXT, nullable: true)]
    private ?string $staffNotes = null;

    #[ORM\Column(name: 'assigned_staff_id', type: Types::BIGINT, nullable: true)]
    private ?int $assignedStaffId = null;

    #[ORM\Column(name: 'created_at', type: Types::DATETIME_MUTABLE)]
    private ?\DateTime $createdAt = null;

    #[ORM\Column(name: 'updated_at', type: Types::DATETIME_MUTABLE)]
    private ?\DateTime $updatedAt = null;

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $this->createdAt ??= new \DateTime();
        $this->updatedAt ??= new \DateTime();
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTime();
    }

    /**
     * Safe projection: client-visible metadata only. Must never carry the
     * secret (encrypted or not) or the internal staff notes.
     */
    public function toApiArray(): array
    {
        return [
            'id' => $this->getId(),
            'client_id' => $this->clientId,
            'client_order_id' => $this->clientOrderId,
            'status' => $this->status,
            'method' => $this->method,
            'panel_type' => $this->panelType,
            'panel_type_label' => PanelType::label($this->panelType),
            'host' => $this->host,
            'port' => $this->port,
            'username' => $this->username,
            'client_notes' => $this->clientNotes,
            'has_secret' => $this->secretEncrypted !== '',
            'secret_purged_at' => $this->secretPurgedAt?->format('Y-m-d H:i:s'),
            'assigned_staff_id' => $this->assignedStaffId,
            'can_client_cancel' => RequestStatus::isClientCancellable($this->status),
            'created_at' => $this->createdAt?->format('Y-m-d H:i:s'),
            'updated_at' => $this->updatedAt?->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * Staff projection: adds internal notes and purge eligibility. Still no
     * secret — that comes only from Service::revealSecret().
     */
    public function toAdminApiArray(): array
    {
        return $this->toApiArray() + [
            'staff_notes' => $this->staffNotes,
            'can_purge_secret' => RequestStatus::isPurgeable($this->status) && $this->secretEncrypted !== '',
        ];
    }

    public function purgeSecret(): self
    {
        $this->secretEncrypted = '';
        $this->secretPurgedAt = new \DateTime();

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): int
    {
        return $this->clientId;
    }

    public function setClientId(int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getClientOrderId(): ?int
    {
        return $this->clientOrderId;
    }

    public function setClientOrderId(?int $clientOrderId): self
    {
        $this->clientOrderId = $clientOrderId;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if (!RequestStatus::isValid($status)) {
            throw new \FOSSBilling\InformationException('Unknown migration request status.');
        }

        $this->status = $status;

        return $this;
    }

    public function getMethod(): string
    {
        return $this->method;
    }

    public function setMethod(string $method): self
    {
        $this->method = $method;

        return $this;
    }

    public function getPanelType(): string
    {
        return $this->panelType;
    }

    public function setPanelType(string $panelType): self
    {
        $this->panelType = $panelType;

        return $this;
    }

    public function getHost(): string
    {
        return $this->host;
    }

    public function setHost(string $host): self
    {
        $this->host = $host;

        return $this;
    }

    public function getPort(): ?int
    {
        return $this->port;
    }

    public function setPort(?int $port): self
    {
        $this->port = $port;

        return $this;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getSecretEncrypted(): string
    {
        return $this->secretEncrypted;
    }

    public function setSecretEncrypted(string $secretEncrypted): self
    {
        $this->secretEncrypted = $secretEncrypted;

        return $this;
    }

    public function getSecretPurgedAt(): ?\DateTime
    {
        return $this->secretPurgedAt;
    }

    public function getClientNotes(): ?string
    {
        return $this->clientNotes;
    }

    public function setClientNotes(?string $clientNotes): self
    {
        $this->clientNotes = $clientNotes;

        return $this;
    }

    public function getStaffNotes(): ?string
    {
        return $this->staffNotes;
    }

    public function setStaffNotes(?string $staffNotes): self
    {
        $this->staffNotes = $staffNotes;

        return $this;
    }

    public function getAssignedStaffId(): ?int
    {
        return $this->assignedStaffId;
    }

    public function setAssignedStaffId(?int $assignedStaffId): self
    {
        $this->assignedStaffId = $assignedStaffId;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }
}
